language: php

php:
  - 5.5
  - 5.6
  - 7

matrix:
  allow_failures:
    - php: 7

before_script:
  - yes "" | pecl install eio
  - echo "extension=\"eio.so\"" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer self-update
  - composer install --dev

script:
  - vendor/bin/phpunit --coverage-text